### ISSUE TITLE
ERROR: From `deldir` Fortran, nerror = 12

### ISSUE THREAD

**Issue by jstarczewski** [robertdj/Deldir.jl#24]
Hey, it's me again still trying to implement DistMesh2D with `DelDir.jl`. Im facing an error when trying to triangulate this set of points
```Julia
julia> using Deldir

julia> p = [0.5 0.5160755806995247; 0.6298693933111951 0.7619232990659295; 3.603303766475108e-10 0.8344458921960469; 0.3747563214394696 0.26077134080526376; 4.686228627370781e-10 0.528377426819142; 0.5 2.1812240902363556e-10; 0.7400581462836814 0.9999999997699264; 0.7250014908241768 0.514876320113826; 0.0 0.0; 0.8714501241159571 0.3172772871707666; 0.2564724726615222 0.006577083476456302; 0.9999999996551774 0.20541792805309989; 0.8704301888460642 0.7198667085381599; 1.0 0.0; 3.4482255939494166e-10 0.20541792805309989; 0.370130606688805 0.7619232990659295; 0.9999999995313771 0.528377426819142; 0.5 0.9999999997130852; 0.6252436785605304 0.26077134080526376; 0.12956981115393584 0.71986670853816; 0.12854987588404299 0.31727728717076664; 1.0 1.0; 0.9999999996396696 0.8344458921960467; 0.27499850917582325 0.5148763201138261; 0.0 1.0; 0.7435275273384778 0.006577083476456302; 0.2599418537163186 0.9999999997699264]

27×2 Array{Float64,2}:
 0.5          0.516076
 0.629869     0.761923
 3.6033e-10   0.834446
 0.374756     0.260771
 4.68623e-10  0.528377
 0.5          2.18122e-10
 0.740058     1.0
 ⋮            
 0.12855      0.317277
 1.0          1.0
 1.0          0.834446
 0.274999     0.514876
 0.0          1.0
 0.743528     0.00657708
 0.259942     1.0

julia> 

julia> julia> del, vor, summ = deldir(p[:,1], p[:,2])
┌ Warning: Fortran error 12
└ @ Deldir ~/.julia/packages/Deldir/MjE6a/src/wrapper.jl:117
ERROR: From `deldir` Fortran, nerror = 12
Stacktrace:
 [1] error(::String, ::Int32) at ./error.jl:42
 [2] deldirwrapper(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}; epsilon::Float64) at /Users/jstarczewski/.julia/packages/Deldir/MjE6a/src/wrapper.jl:119
 [3] deldirwrapper at /Users/jstarczewski/.julia/packages/Deldir/MjE6a/src/wrapper.jl:149 [inlined] (repeats 2 times)
 [4] deldir(::Array{Float64,1}, ::Array{Float64,1}; args::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/jstarczewski/.julia/packages/Deldir/MjE6a/src/wrapper.jl:221
 [5] deldir(::Array{Float64,1}, ::Array{Float64,1}) at /Users/jstarczewski/.julia/packages/Deldir/MjE6a/src/wrapper.jl:221
 [6] top-level scope at none:1

julia> 
```
I work on MacOs Catalina.

**Comment by robertdj** [comment]
It seems you have a gift for finding points that are difficult to handle :-) 
The error number 12 is not documented in the R package, so I don't know what it means :-( 

As I commented in issue https://github.com/robertdj/Deldir.jl/issues/23 it turns out to be difficult to use newer version of the Fortran code due to tighter coupling with R. 
Can you try running the latest version of the R package with those points? If the R package can handle it there is a good reason to look more into making the code work with Julia.

**Comment by jstarczewski** [comment]
@robertdj Hey, I tried to run `DelDir` with given points using R and it seems to work.
```R
library(ggplot2)
library(deldir)

# Use stdout as per normal...
print("Hello, world!")

x <- c(0.5, 0.6298693933111951, 3.603303766475108e-10, 0.3747563214394696, 4.686228627370781e-10, 0.5, 0.7400581462836814, 0.7250014908241768, 0.0, 0.8714501241159571, 0.2564724726615222, 0.9999999996551774, 0.8704301888460642, 1.0, 3.4482255939494166e-10, 0.370130606688805, 0.9999999995313771, 0.5, 0.6252436785605304, 0.12956981115393584, 0.12854987588404299, 1.0, 0.9999999996396696, 0.27499850917582325, 0.0, 0.7435275273384778, 0.2599418537163186)
y <- c(0.5160755806995247, 0.7619232990659295, 0.8344458921960469, 0.26077134080526376, 0.528377426819142, 2.1812240902363556e-10, 0.9999999997699264, 0.514876320113826, 0.0, 0.3172772871707666, 0.006577083476456302, 0.20541792805309989, 0.7198667085381599, 0.0, 0.20541792805309989, 0.7619232990659295, 0.528377426819142, 0.9999999997130852, 0.26077134080526376, 0.71986670853816, 0.31727728717076664, 1.0, 0.8344458921960467, 0.5148763201138261, 1.0, 0.006577083476456302, 0.9999999997699264)
dxy1 <- deldir(x,y)
plot(dxy1)
```
**Please note that I used [this online editor](https://rdrr.io/snippets/) to run code and I have nearly no knowledge about R lang. Thats why I am using matrices instead of DataFrames in the example above**
Here is the output graph, which I think is correct, because I was trying to plot rectangle mesh :D 
![image](https://user-images.githubusercontent.com/36159919/98446981-d53b4200-2121-11eb-9901-ecf9603f99ce.png)

**Comment by robertdj** [comment]
Thanks for trying this out. It turns out that it works in R even in older versions of the `deldir` package. 
Let me look more into the differences between the calls in R and Julia.

**Comment by robertdj** [comment]
@jstarczewski : I haven't had time to find a solution yet (it's all spare time), but I'll keep you posted.

**Comment by robertdj** [comment]
I have found the issue: In R we have the `sort` argument which according to the docs:

> Logical argument; if TRUE (the default) the data (including dummy points) are sorted into a sequence of “bins” prior to triangulation; this makes the algorithm slightly more efficient. Normally one would set sort equal to FALSE only if one wished to observe some of the fine detail of the way in which adding a point to a data set affected the triangulation, and therefore wished to make sure that the point in question was added last. Essentially this argument would get used only in a de-bugging process.

With `sort = TRUE` the functions work in R. However, with deldir version 0.1-15 in R:

```
> deldir::deldir(x, y, rw = c(0, 1, 0, 1), sort = FALSE)
nerror = 12 
```

With deldir version 0.2-2 in R
```
> dxy1 <- deldir::deldir(x, y, rw = c(0, 1, 0, 1), sort = FALSE)
Vertices of triangle are collinear.
```

Let me look into calling the same sorting routine here in *Deldir*.

**Comment by robertdj** [comment]
Your troublesome data now works On My Machine. You can try it out by installing from the branch `sort`.

Unfortunately, the Registrator doesn't react to my registration, so the fix cannot be made official right now.

**Comment by jstarczewski** [comment]
@robertdj Tried solution from `sort` branch and it <b>works</b> works well generating meshes, thank you for your help!
When will you register your fix officially?
![image](https://user-images.githubusercontent.com/36159919/99569880-799a6f80-29d1-11eb-9dc2-db7f01a2d5c5.png)

**Comment by robertdj** [comment]
I have just made a PR. When Travis is done testing I will merge and submit a registration.
